Vagrant.configure("2") do |config|

	config.vm.box = "spox/ubuntu-arm"

	config.vm.network "private_network", ip: "192.168.33.12"
	config.vm.network "public_network"

	config.vm.provider "virtualbox" do |vb|
		vb.cpus = 1
		vb.memory = "2048"
	end

	config.vm.provision :shell, path: 'provision.sh'

end
