Vagrant.configure("2") do |config|

	config.vm.box = "jacobw/fedora35-arm64"

	config.vm.network "private_network", ip: "192.168.33.10"
	config.vm.network "public_network"

	config.vm.provider "virtualbox" do |vb|
		vb.memory = "2048"
	end

	config.vm.provision "shell", inline: <<-SHELL
		sudo wget -O /etc/yum.repos.d/jenkins.repo https://pkg.jenkins.io/redhat-stable/jenkins.repo
		sudo rpm --import https://pkg.jenkins.io/redhat-stable/jenkins.io-2023.key

		sudo yum install fontconfig java-11-openjdk -y
		sudo yum install jenkins -y

		sudo systemctl start jenkins
		sudo systemctl enable jenkins
		sudo systemctl daemon-reload

		sudo firewall-cmd --add-port=8080/tcp --permanent
		sudo firewall-cmd --reload

		sudo systemctl restart jenkins
	SHELL

end
